### PR TITLE
Db item quantity

### PR DESCRIPTION
**Pull request by qgerome**

### CODE REVIEW

**Review by edarchis — APPROVED** [review]
Well spotted

**Review by edarchis — CHANGES_REQUESTED** [review]
Wait, the test yields:
```
 1 Msg 515, Level 16, State 2, Server 302d9d2f2ba1, Line 151
      1 Cannot insert the value NULL into column 'ItemQuantity', table 'test_imis.dbo.tblItems'; column does not allow nulls. INSERT fails.
```

**Comment by qgerome** [comment]
> Wait, the test yields:
> 
> ```
>  1 Msg 515, Level 16, State 2, Server 302d9d2f2ba1, Line 151
>       1 Cannot insert the value NULL into column 'ItemQuantity', table 'test_imis.dbo.tblItems'; column does not allow nulls. INSERT fails.
> ```

I've fixed the name of the column and changed it to a nullable column (as in the migration script)

**Review by edarchis — APPROVED** [review]
Looks good now. Some tests are still failing but due to other modules

**Pull request merged**
